### ISSUE TITLE
Change location of ledger install.

### ISSUE THREAD

**Issue by albertl2** [slashdotdash/node-ledger-import#3]
It would be very useful to point this program at the location of the ledger installation. I am unsure as to how I ought to proceed in making this change.

**Comment by slashdotdash** [comment]
@zo34 The import uses the [node-ledger](https://github.com/slashdotdash/node-ledger) library, which can be provided with the path to the Legder binary.

Unfortunately this is not currently supported by the import tool. It would only be a small change, so I will take a look for you.
