### ISSUE TITLE
throw er; //Unhandled 'error' event

### ISSUE THREAD

**Issue by alexjj** [slashdotdash/node-ledger-import#4]
Not sure what's wrong but tried running ledger-import and I get the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/ledger ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

Any suggestions?

**Comment by slashdotdash** [comment]
Do you have [Ledger CLI](http://www.ledger-cli.org/) installed? 

The error seems to indicate that the import could not find the `ledger` binary (from `/usr/local/bin/ledger`).

If you have Ledger installed in a different location (`which ledger`) then you can run the import with the following argument:

```
 --ledger-binary <path>
```

**Comment by alexjj** [comment]
Okay. Ledger is installed to `/usr/bin/ledger` for me.
